export const blogPosts = [
    {
        id: 'b1',
        slug: 'why-handmade-soap-is-better-for-your-skin',
        title: 'Why Handmade Soap Is Better For Your Skin',
        excerpt: 'Mass-produced commercial soap bars often strip your skin of natural oils. Here is what makes cold-processed handmade soap different.',
        coverImage: 'https://picsum.photos/seed/blog-handmade-soap/900/560',
        author: 'Team SoapVeda',
        date: '2026-06-01',
        category: 'Skincare Tips',
        readTime: '4 min read',
        tags: ['handmade soap', 'skincare', 'natural ingredients'],
        metaDescription: 'Discover why cold-processed handmade soap is gentler and more nourishing for your skin than mass-produced commercial bars.',
        content: [
            'Walk down any supermarket aisle and you will find rows of soap bars promising softer skin - yet most are detergent-based bars that have had glycerin (a natural byproduct of soap making) removed and sold separately. This is one of the biggest differences between commercial and handmade soap.',
            'When soap is made the traditional way - by combining oils with an alkali through a process called saponification - it naturally produces glycerin, a humectant that draws moisture into the skin. Handmade soap makers keep this glycerin in the bar instead of extracting it, which is a big part of why handmade soap tends to feel more moisturizing.',
            'Cold-processed soap is also cured for four to six weeks before it is sold. This curing time allows excess water to evaporate, resulting in a harder, longer-lasting bar with a milder, more balanced pH than many commercial bars.',
            'Because handmade soap is made in small batches, makers have full control over the ingredients that go in - real botanical oils, herbal extracts and essential oils - rather than synthetic fragrances and preservative-heavy formulas.',
            'If you have sensitive or easily irritated skin, switching to a gentle, cold-processed handmade soap free of sulfates and synthetic detergents is one of the simplest changes you can make to your routine.',
        ],
    },
    {
        id: 'b2',
        slug: 'how-to-start-a-soap-making-business-from-home',
        title: 'How To Start A Soap Making Business From Home',
        excerpt: 'Thinking of turning your soap making hobby into a business? Here is a practical, step-by-step starting point.',
        coverImage: 'https://picsum.photos/seed/blog-soap-business/900/560',
        author: 'Priya Deshmukh',
        date: '2026-05-18',
        category: 'Business',
        readTime: '6 min read',
        tags: ['soap business', 'entrepreneurship', 'small business'],
        metaDescription: 'A practical step-by-step guide to starting a handmade soap business from home, from recipe testing to your first sale.',
        content: [
            'Turning a soap making hobby into an income stream is more achievable today than ever, thanks to social media and online marketplaces. But a successful soap business needs more than a good recipe - it needs a plan.',
            'Start by nailing down 3-4 signature recipes that you can make consistently. Test batches on friends and family, gather honest feedback, and refine your formulas before you ever sell your first bar.',
            'Next, understand your local regulations around cosmetic labeling and small-scale manufacturing. Requirements vary by state and country, so it is worth spending a weekend researching (or consulting a professional) before you scale up.',
            'Pricing is where many new soap makers struggle. Make sure your price covers raw materials, packaging, your time, and a reasonable margin - underpricing handmade goods is one of the most common early mistakes.',
            'Finally, invest in simple, consistent packaging and product photography. Buyers cannot smell or touch your soap online, so your photos and descriptions have to do that work for you.',
            "If you want a structured starting point, our Beginner's Soap Making Kit includes a step-by-step guide covering recipe basics, curing and packaging.",
        ],
    },
    {
        id: 'b3',
        slug: 'cold-process-vs-melt-and-pour-soap-making',
        title: 'Cold Process vs Melt & Pour: Which Soap Making Method Should You Choose?',
        excerpt: 'Both methods produce beautiful soap, but they suit different goals, budgets and patience levels. Here is how to decide.',
        coverImage: 'https://picsum.photos/seed/blog-cold-process-vs-melt-pour/900/560',
        author: 'Team SoapVeda',
        date: '2026-04-30',
        category: 'Soap Making',
        readTime: '5 min read',
        tags: ['cold process', 'melt and pour', 'soap making basics'],
        metaDescription: 'Compare cold process and melt & pour soap making methods to decide which is the right starting point for you.',
        content: [
            'If you are new to soap making, one of the first decisions you will face is choosing between cold process and melt & pour methods - and there is no single right answer.',
            'Melt & pour uses a pre-made base that you simply melt, add color and fragrance to, then pour into moulds. It sets within hours and requires no handling of lye, making it the more approachable choice for beginners, kids-supervised projects, and anyone who wants quick results.',
            'Cold process, on the other hand, involves mixing oils with a lye solution to trigger saponification from scratch. It offers far more control over ingredients and texture but requires careful safety precautions when handling lye, and bars need to cure for four to six weeks before use.',
            'If you are soap making as a hobby or want to sell quickly, melt & pour is a great entry point using our soap bases. If you want maximum creative control over ingredients and are ready to invest in curing time, cold process is worth learning - our Advanced Cold Process Soap Kit is built exactly for this.',
            'Many of our own bestsellers, in fact, use cold process for its skin-loving glycerin content, while our soap making kits offer both options so you can try each method yourself.',
        ],
    },
    {
        id: 'b4',
        slug: 'beginners-guide-to-essential-oils-in-soap-making',
        title: "A Beginner's Guide To Using Essential Oils In Soap Making",
        excerpt: 'Essential oils add scent and skin-loving properties to handmade soap - but using them correctly matters. Here is what to know.',
        coverImage: 'https://picsum.photos/seed/blog-essential-oils-guide/900/560',
        author: 'Team SoapVeda',
        date: '2026-04-09',
        category: 'Soap Making',
        readTime: '5 min read',
        tags: ['essential oils', 'soap making', 'fragrance'],
        metaDescription: 'Learn how to safely and effectively use essential oils in your handmade soap recipes, including usage rates and popular choices.',
        content: [
            'Essential oils are one of the most popular ways to scent handmade soap naturally, but getting the usage rate right takes a little know-how.',
            'As a general starting point, most soap makers use 8-10ml of essential oil per 1kg of soap base or oils, added at trace (the point where the mixture thickens slightly). Rates can vary depending on the oil\'s strength - stronger oils like clove or cinnamon are used more sparingly.',
            'Lavender, tea tree, rosemary and peppermint are popular beginner-friendly choices because they are well-tolerated, widely available and blend well with herbal soap recipes.',
            'Always source oils that are labeled 100% pure and undiluted for soap making, and be mindful that not every essential oil is suitable for leave-on skin products at high concentrations.',
            'If you are experimenting for the first time, start with a single oil in a small test batch before committing to a full recipe - this way you can judge scent strength (which softens slightly after curing) before scaling up.',
        ],
    },
    {
        id: 'b5',
        slug: '7-natural-ingredients-for-naturally-glowing-skin',
        title: '7 Natural Ingredients For Naturally Glowing Skin',
        excerpt: 'From rose to manjistha, these time-tested natural ingredients have earned their place in Indian skincare routines for good reason.',
        coverImage: 'https://picsum.photos/seed/blog-glowing-skin/900/560',
        author: 'Team SoapVeda',
        date: '2026-03-22',
        category: 'Skincare Tips',
        readTime: '4 min read',
        tags: ['natural skincare', 'ayurveda', 'glowing skin'],
        metaDescription: 'A round-up of 7 natural, Ayurveda-backed ingredients - from rose to manjistha - for naturally glowing skin.',
        content: [
            '1. Multani Mitti (Fuller\'s Earth) - A cooling clay that absorbs excess oil and leaves skin feeling refreshed, especially useful in humid climates.',
            '2. Manjistha - An Ayurvedic root powder traditionally used in face packs to help even out skin tone.',
            '3. Rose - Both as rose water and rose petal powder, rose is prized for its gentle, hydrating and calming properties.',
            '4. Turmeric - A staple of Indian skincare, used in small amounts for its traditional purifying reputation.',
            '5. Neem - Known for its purifying properties, popular in soaps and face packs for blemish-prone skin.',
            '6. Kaolin Clay - A gentle clay suitable even for sensitive skin, unlike stronger clays that can be over-drying.',
            '7. Shea Butter - A rich, plant-based butter that helps replenish moisture, especially valuable in soap bars for dry skin.',
            'Many of these ingredients feature directly in our handmade soap and herbal powder ranges - a simple way to bring traditional skincare into your everyday routine.',
        ],
    },
];
export const getBlogPostBySlug = (slug) => blogPosts.find((b) => b.slug === slug);
export const blogCategories = ['All', ...Array.from(new Set(blogPosts.map((b) => b.category)))];
