export const initialCoupons = [
    {
        id: 'coup-1',
        code: 'WELCOME10',
        type: 'percent',
        value: 10,
        minOrderValue: 499,
        maxDiscount: 200,
        expiryDate: '2026-12-31',
        active: true,
        usageLimit: 1000,
        usedCount: 214,
    },
    {
        id: 'coup-2',
        code: 'SOAP50',
        type: 'flat',
        value: 50,
        minOrderValue: 399,
        expiryDate: '2026-12-31',
        active: true,
        usageLimit: 500,
        usedCount: 87,
    },
    {
        id: 'coup-3',
        code: 'BULK20',
        type: 'percent',
        value: 20,
        minOrderValue: 2000,
        maxDiscount: 500,
        expiryDate: '2026-12-31',
        active: true,
        usageLimit: 200,
        usedCount: 32,
    },
    {
        id: 'coup-4',
        code: 'FESTIVE15',
        type: 'percent',
        value: 15,
        minOrderValue: 999,
        maxDiscount: 300,
        expiryDate: '2026-11-15',
        active: true,
        usageLimit: 300,
        usedCount: 58,
    },
];
export const initialBanners = [
    {
        id: 'ban-1',
        title: 'Nature-First Skincare, Handmade in Small Batches',
        subtitle: 'Cold-processed soaps & herbal skincare crafted with real botanicals - no sulfates, no parabens.',
        image: 'https://picsum.photos/seed/hero-banner-1/1600/900',
        ctaLabel: 'Shop Bestsellers',
        ctaLink: '/shop',
        active: true,
        position: 'hero',
    },
    {
        id: 'ban-2',
        title: 'Buy 2 Get 1 Free On Handmade Soaps',
        subtitle: 'Mix & match any 3 handmade soap bars and the cheapest one is free - no coupon code needed.',
        image: 'https://picsum.photos/seed/hero-banner-2/1600/900',
        ctaLabel: 'Shop The Offer',
        ctaLink: '/shop?category=handmade-soaps',
        active: true,
        position: 'hero',
    },
    {
        id: 'ban-3',
        title: 'Flat 20% Off Soap Making Kits & Ingredients',
        subtitle: 'Stock up on soap bases, herbal powders and essential oils at 20% off this week only.',
        image: 'https://picsum.photos/seed/hero-banner-3/1600/900',
        ctaLabel: 'Shop The Sale',
        ctaLink: '/shop?category=soap-making-kits',
        active: true,
        position: 'hero',
    },
    {
        id: 'ban-4',
        title: 'Free Shipping Over \u20B9999',
        subtitle: 'Stock up on soap making raw materials and save on delivery.',
        image: 'https://picsum.photos/seed/promo-banner-1/1200/500',
        ctaLabel: 'Shop Raw Materials',
        ctaLink: '/shop?category=soap-bases',
        active: true,
        position: 'promo',
    },
];
