export const products = [
    {
        id: 'p1',
        slug: 'lavender-bliss-handmade-soap',
        name: 'Lavender Bliss Handmade Soap',
        category: 'handmade-soaps',
        images: [
            'https://picsum.photos/seed/p1-lavender-soap-a/800/800',
            'https://picsum.photos/seed/p1-lavender-soap-b/800/800',
            'https://picsum.photos/seed/p1-lavender-soap-c/800/800',
        ],
        shortDescription: 'Cold-processed soap infused with French lavender oil and shea butter for silky, calm skin.',
        description: 'Our best-selling bar is handcrafted using the traditional cold-process method and cured for six weeks to create a long-lasting, richly lathering soap. French lavender essential oil and real dried lavender buds bring a soft floral aroma while shea butter keeps skin nourished instead of stripped.',
        benefits: [
            'Gently cleanses without stripping natural oils',
            'Calms and soothes stressed or irritated skin',
            'Light, relaxing lavender aroma for a spa-like shower',
            'Handmade in small batches using the cold-process method',
        ],
        ingredients: ['Saponified Coconut & Olive Oil', 'Shea Butter', 'Lavender Essential Oil', 'Dried Lavender Buds', 'Vitamin E'],
        howToUse: [
            'Wet the soap bar and your skin with lukewarm water.',
            'Rub gently between palms or a loofah to build a rich lather.',
            'Massage onto skin in circular motions for 30-60 seconds.',
            'Rinse thoroughly and pat dry.',
            'Store on a well-drained soap dish between uses to extend bar life.',
        ],
        variants: [
            { id: 'p1-v1', label: 'Single Bar - 100g', price: 199, comparePrice: 249, stock: 120, sku: 'SV-SOAP-LAV-100' },
            { id: 'p1-v2', label: 'Pack of 3', price: 549, comparePrice: 597, stock: 60, sku: 'SV-SOAP-LAV-3PK' },
            { id: 'p1-v3', label: 'Pack of 5', price: 849, comparePrice: 995, stock: 30, sku: 'SV-SOAP-LAV-5PK' },
        ],
        rating: 4.7,
        reviews: [
            { id: 'p1-r1', author: 'Ananya S.', rating: 5, date: '2026-05-12', title: 'So gentle!', comment: 'My skin has never felt this soft. The lavender scent is calming without being overpowering.', verified: true },
            { id: 'p1-r2', author: 'Rohit K.', rating: 4, date: '2026-04-02', comment: 'Lovely soap, lathers well. Wish the bars were slightly bigger.', verified: true },
        ],
        tags: ['bestseller', 'herbal', 'cold-process'],
        featured: true,
        bestseller: true,
    },
    {
        id: 'p2',
        slug: 'neem-tulsi-purifying-soap',
        name: 'Neem Tulsi Purifying Soap',
        category: 'handmade-soaps',
        images: [
            'https://picsum.photos/seed/p2-neem-soap-a/800/800',
            'https://picsum.photos/seed/p2-neem-soap-b/800/800',
            'https://picsum.photos/seed/p2-neem-soap-c/800/800',
        ],
        shortDescription: 'A purifying blend of neem and tulsi to fight blemishes and keep skin clear.',
        description: 'Formulated for acne-prone and oily skin, this bar blends neem oil and tulsi (holy basil) extract - two herbs trusted in Indian households for generations - with turmeric to help purify and balance skin without over-drying it.',
        benefits: ['Helps combat acne-causing bacteria', 'Purifies and detoxifies skin', 'Tulsi helps soothe inflammation', 'Suitable for oily & acne-prone skin'],
        ingredients: ['Saponified Coconut & Castor Oil', 'Neem Oil', 'Tulsi Extract', 'Turmeric', 'Vitamin E'],
        howToUse: [
            'Wet face or body and the soap bar with lukewarm water.',
            'Lather well between hands and apply to skin.',
            'Leave on for 20-30 seconds for the actives to work.',
            'Rinse thoroughly and pat dry.',
        ],
        variants: [
            { id: 'p2-v1', label: 'Single Bar - 100g', price: 179, comparePrice: 219, stock: 140, sku: 'SV-SOAP-NEEM-100' },
            { id: 'p2-v2', label: 'Pack of 3', price: 499, comparePrice: 537, stock: 70, sku: 'SV-SOAP-NEEM-3PK' },
            { id: 'p2-v3', label: 'Pack of 5', price: 799, comparePrice: 895, stock: 25, sku: 'SV-SOAP-NEEM-5PK' },
        ],
        rating: 4.5,
        reviews: [
            { id: 'p2-r1', author: 'Sneha P.', rating: 5, date: '2026-03-21', comment: 'Cleared up my back acne in a couple of weeks. Smells earthy and clean.', verified: true },
            { id: 'p2-r2', author: 'Imran A.', rating: 4, date: '2026-02-11', comment: 'Works well, a bit drying if used twice a day so I moisturize after.', verified: true },
        ],
        tags: ['bestseller', 'acne-care'],
        bestseller: true,
    },
    {
        id: 'p3',
        slug: 'activated-charcoal-detox-soap',
        name: 'Activated Charcoal Detox Soap',
        category: 'handmade-soaps',
        images: [
            'https://picsum.photos/seed/p3-charcoal-soap-a/800/800',
            'https://picsum.photos/seed/p3-charcoal-soap-b/800/800',
            'https://picsum.photos/seed/p3-charcoal-soap-c/800/800',
        ],
        shortDescription: 'Deep-cleansing charcoal soap that draws out impurities and excess oil.',
        description: 'Activated bamboo charcoal acts like a magnet for dirt, pollution and excess sebum, leaving skin feeling deeply cleansed and refreshed. Paired with tea tree oil and kaolin clay for a balanced, mattifying finish.',
        benefits: ['Draws out dirt & pollutants', 'Controls excess oil & shine', 'Leaves skin matte & refreshed', 'Suitable for normal to oily skin'],
        ingredients: ['Activated Bamboo Charcoal', 'Saponified Coconut & Sunflower Oil', 'Tea Tree Oil', 'Kaolin Clay'],
        howToUse: ['Wet skin and soap with water.', 'Lather and massage onto face or body.', 'Avoid direct eye contact.', 'Rinse well and follow with moisturizer.'],
        variants: [
            { id: 'p3-v1', label: 'Single Bar - 100g', price: 199, comparePrice: 239, stock: 100, sku: 'SV-SOAP-CHAR-100' },
            { id: 'p3-v2', label: 'Pack of 3', price: 549, comparePrice: 597, stock: 45, sku: 'SV-SOAP-CHAR-3PK' },
        ],
        rating: 4.6,
        reviews: [{ id: 'p3-r1', author: 'Devika R.', rating: 5, date: '2026-06-02', comment: 'My oily T-zone finally feels under control. Love the matte finish.', verified: true }],
        tags: ['new', 'detox'],
        newArrival: true,
    },
    {
        id: 'p4',
        slug: 'rose-kaolin-clay-soap',
        name: 'Rose Kaolin Clay Soap',
        category: 'handmade-soaps',
        images: [
            'https://picsum.photos/seed/p4-rose-soap-a/800/800',
            'https://picsum.photos/seed/p4-rose-soap-b/800/800',
            'https://picsum.photos/seed/p4-rose-soap-c/800/800',
        ],
        shortDescription: 'A pampering rose-infused clay soap for a soft, glowing complexion.',
        description: 'Kaolin clay gently polishes away dull, tired skin while rose petal powder and rose absolute leave behind a delicate floral scent and a subtle glow - a little self-care ritual in every shower.',
        benefits: ['Gently exfoliates dull skin', 'Improves skin tone & texture over time', 'Delicate floral aroma', 'Rich in antioxidants'],
        ingredients: ['Saponified Olive & Almond Oil', 'Kaolin Clay', 'Rose Petal Powder', 'Rose Absolute', 'Glycerin'],
        howToUse: ['Wet the bar and skin.', 'Lather gently and massage in circular motions to exfoliate.', 'Rinse thoroughly.', 'Use 3-4 times a week for best results.'],
        variants: [
            { id: 'p4-v1', label: 'Single Bar - 100g', price: 219, comparePrice: 259, stock: 90, sku: 'SV-SOAP-ROSE-100' },
            { id: 'p4-v2', label: 'Pack of 3', price: 599, comparePrice: 657, stock: 40, sku: 'SV-SOAP-ROSE-3PK' },
            { id: 'p4-v3', label: 'Pack of 5', price: 929, comparePrice: 1095, stock: 20, sku: 'SV-SOAP-ROSE-5PK' },
        ],
        rating: 4.8,
        reviews: [{ id: 'p4-r1', author: 'Kavya N.', rating: 5, date: '2026-05-29', title: 'Gorgeous scent', comment: 'Feels luxurious and smells amazing. My new favorite gifting soap.', verified: true }],
        tags: ['featured', 'gifting'],
        featured: true,
    },
    {
        id: 'p5',
        slug: 'herbal-amla-reetha-shampoo',
        name: 'Herbal Amla Reetha Shampoo',
        category: 'shampoo',
        images: ['https://picsum.photos/seed/p5-amla-shampoo-a/800/800', 'https://picsum.photos/seed/p5-amla-shampoo-b/800/800', 'https://picsum.photos/seed/p5-amla-shampoo-c/800/800'],
        shortDescription: 'Sulfate-free shampoo with amla & reetha for stronger, shinier hair.',
        description: 'A gentle, sulfate-free cleanser built around three Ayurvedic classics - amla, reetha (soapnut) and shikakai - that clean hair and scalp without stripping away natural oils, leaving hair soft and manageable.',
        benefits: ['Cleanses without stripping natural oils', 'Strengthens hair from root to tip', 'Adds natural shine', 'Sulfate & paraben free'],
        ingredients: ['Aqua', 'Coco Glucoside (plant-based cleanser)', 'Amla Extract', 'Reetha (Soapnut) Extract', 'Shikakai Extract', 'Hibiscus Extract'],
        howToUse: ['Wet hair thoroughly.', 'Apply a small amount and massage into scalp.', 'Lather and rinse well.', 'Follow with conditioner or hair oil if needed.'],
        variants: [
            { id: 'p5-v1', label: '100ml', price: 249, comparePrice: 299, stock: 80, sku: 'SV-SHMP-AMLA-100' },
            { id: 'p5-v2', label: '200ml', price: 449, comparePrice: 529, stock: 55, sku: 'SV-SHMP-AMLA-200' },
        ],
        rating: 4.4,
        reviews: [{ id: 'p5-r1', author: 'Priyanka D.', rating: 4, date: '2026-04-18', comment: 'Lathers less than regular shampoo (expected since sulfate-free) but hair feels healthier.', verified: true }],
        tags: ['bestseller'],
        bestseller: true,
    },
    {
        id: 'p6',
        slug: 'onion-hair-fall-control-shampoo',
        name: 'Onion Hair Fall Control Shampoo',
        category: 'shampoo',
        images: ['https://picsum.photos/seed/p6-onion-shampoo-a/800/800', 'https://picsum.photos/seed/p6-onion-shampoo-b/800/800', 'https://picsum.photos/seed/p6-onion-shampoo-c/800/800'],
        shortDescription: 'Red onion extract shampoo to reduce hair fall and boost volume.',
        description: 'Red onion extract is rich in sulfur compounds traditionally used to support scalp health. Combined with black seed oil and curry leaf extract, this shampoo targets hair fall while keeping hair voluminous and soft.',
        benefits: ['Helps reduce hair fall with regular use', 'Nourishes and balances the scalp', 'Adds volume & thickness', 'Sulfate-free formula'],
        ingredients: ['Aqua', 'Red Onion Extract', 'Black Seed Oil', 'Curry Leaf Extract', 'Coco Glucoside'],
        howToUse: ['Wet hair and scalp.', 'Massage a coin-sized amount into scalp for 1-2 minutes.', 'Rinse thoroughly, repeat if needed.'],
        variants: [
            { id: 'p6-v1', label: '100ml', price: 279, comparePrice: 329, stock: 75, sku: 'SV-SHMP-ONION-100' },
            { id: 'p6-v2', label: '200ml', price: 499, comparePrice: 579, stock: 40, sku: 'SV-SHMP-ONION-200' },
        ],
        rating: 4.3,
        reviews: [{ id: 'p6-r1', author: 'Farhan S.', rating: 4, date: '2026-03-05', comment: 'Noticed less hair on my pillow after about a month of regular use.', verified: true }],
        tags: [],
    },
    {
        id: 'p7',
        slug: 'bhringraj-hair-growth-oil',
        name: 'Bhringraj Hair Growth Oil',
        category: 'hair-oil',
        images: ['https://picsum.photos/seed/p7-bhringraj-oil-a/800/800', 'https://picsum.photos/seed/p7-bhringraj-oil-b/800/800', 'https://picsum.photos/seed/p7-bhringraj-oil-c/800/800'],
        shortDescription: 'Ayurvedic oil blend to nourish roots and encourage healthy hair growth.',
        description: 'A slow-infused blend of bhringraj, curry leaves and fenugreek in a coconut oil base - a classic Ayurvedic combination used for generations to nourish hair follicles and support healthier-looking growth over time.',
        benefits: ['Nourishes hair follicles', 'Helps reduce hair fall over time', 'Adds natural shine', 'Light, non-sticky formula'],
        ingredients: ['Coconut Oil', 'Bhringraj Extract', 'Curry Leaves', 'Fenugreek', 'Castor Oil', 'Vitamin E'],
        howToUse: ['Section hair and apply oil directly to scalp.', 'Massage in circular motions for 5-10 minutes.', 'Leave on for at least 1 hour, or overnight for deep conditioning.', 'Wash off with a mild shampoo.'],
        variants: [
            { id: 'p7-v1', label: '100ml', price: 349, comparePrice: 399, stock: 90, sku: 'SV-OIL-BHRI-100' },
            { id: 'p7-v2', label: '200ml', price: 599, comparePrice: 699, stock: 50, sku: 'SV-OIL-BHRI-200' },
        ],
        rating: 4.6,
        reviews: [{ id: 'p7-r1', author: 'Divya M.', rating: 5, date: '2026-05-02', comment: 'Genuinely reduced my hair fall in about six weeks. Smells earthy, not medicinal.', verified: true }],
        tags: ['bestseller'],
        bestseller: true,
    },
    {
        id: 'p8',
        slug: 'rosemary-scalp-therapy-oil',
        name: 'Rosemary Scalp Therapy Oil',
        category: 'hair-oil',
        images: ['https://picsum.photos/seed/p8-rosemary-oil-a/800/800', 'https://picsum.photos/seed/p8-rosemary-oil-b/800/800', 'https://picsum.photos/seed/p8-rosemary-oil-c/800/800'],
        shortDescription: 'Lightweight rosemary-infused oil to invigorate the scalp for thicker-looking hair.',
        description: 'A fast-absorbing sesame oil base infused with rosemary and peppermint essential oils to invigorate the scalp, ideal for anyone dealing with a dry or flaky scalp who wants a lighter alternative to heavier hair oils.',
        benefits: ['Stimulates & invigorates the scalp', 'Helpful for dandruff-prone scalp', 'Lightweight & fast-absorbing', 'With cold-pressed rosemary oil'],
        ingredients: ['Sesame Oil', 'Rosemary Essential Oil', 'Peppermint Oil', 'Vitamin E'],
        howToUse: ['Apply a few drops directly to scalp.', 'Massage for 5 minutes to boost circulation.', 'Can be left in or washed out after 30 minutes.'],
        variants: [{ id: 'p8-v1', label: '100ml', price: 399, comparePrice: 449, stock: 60, sku: 'SV-OIL-ROSM-100' }],
        rating: 4.5,
        reviews: [{ id: 'p8-r1', author: 'Aditi V.', rating: 4, date: '2026-06-10', comment: 'Love how light it feels, no greasy residue. Scalp feels fresher.', verified: true }],
        tags: ['new'],
        newArrival: true,
    },
    {
        id: 'p9',
        slug: 'melt-pour-goat-milk-soap-base',
        name: 'Melt & Pour Goat Milk Soap Base',
        category: 'soap-bases',
        images: ['https://picsum.photos/seed/p9-goatmilk-base-a/800/800', 'https://picsum.photos/seed/p9-goatmilk-base-b/800/800', 'https://picsum.photos/seed/p9-goatmilk-base-c/800/800'],
        shortDescription: 'Creamy goat milk soap base for DIY soap makers - melts smoothly, sets firm.',
        description: 'A creamy, opaque melt & pour base made with real goat milk for soap makers who want a moisturizing, sensitive-skin-friendly bar without the wait time of cold process. Melts smoothly and sets to a firm, long-lasting bar.',
        benefits: ['Rich, creamy lather', 'Great for sensitive skin formulations', 'Easy melt & pour workflow - ready same day', 'SLS & paraben free base'],
        ingredients: ['Goat Milk', 'Glycerin', 'Saponified Oils', 'Sorbitol', 'Purified Water'],
        howToUse: [
            'Cut the base into small cubes for even melting.',
            'Melt in a double boiler or microwave in 20-second bursts until liquid (around 55-60°C).',
            'Add fragrance oil and colorant once cooled slightly to around 50°C.',
            'Pour into moulds and leave to set for 2-4 hours before unmoulding.',
        ],
        variants: [
            { id: 'p9-v1', label: '500g', price: 249, comparePrice: 289, stock: 150, sku: 'SV-BASE-GOAT-500' },
            { id: 'p9-v2', label: '1kg', price: 449, comparePrice: 519, stock: 100, sku: 'SV-BASE-GOAT-1KG' },
            { id: 'p9-v3', label: '5kg (Bulk)', price: 1999, comparePrice: 2299, stock: 30, sku: 'SV-BASE-GOAT-5KG' },
        ],
        rating: 4.7,
        reviews: [{ id: 'p9-r1', author: 'Karan M.', rating: 5, date: '2026-04-22', comment: 'Sets beautifully and my customers love the creamy lather. Great quality base.', verified: true }],
        tags: ['for-soap-makers', 'bestseller'],
        bestseller: true,
    },
    {
        id: 'p10',
        slug: 'transparent-glycerin-soap-base',
        name: 'Transparent Glycerin Soap Base',
        category: 'soap-bases',
        images: ['https://picsum.photos/seed/p10-glycerin-base-a/800/800', 'https://picsum.photos/seed/p10-glycerin-base-b/800/800', 'https://picsum.photos/seed/p10-glycerin-base-c/800/800'],
        shortDescription: 'Crystal-clear glycerin base ideal for embed designs and colorful DIY soaps.',
        description: 'A high-clarity glycerin melt & pour base perfect for layered, embedded and brightly colored soap designs. Neutral scent leaves plenty of room to build your own fragrance blends.',
        benefits: ['High clarity & shine', 'Excellent for embeds & layering', 'Neutral base scent - blends well with fragrance oils', 'Low-sweat formulation'],
        ingredients: ['Glycerin', 'Saponified Coconut Oil', 'Sorbitol', 'Sucrose', 'Purified Water'],
        howToUse: ['Cut into cubes and melt gently (avoid boiling to reduce cloudiness).', 'Add colorant/fragrance around 50°C.', 'Pour into moulds and allow to set fully before unmoulding.'],
        variants: [
            { id: 'p10-v1', label: '500g', price: 229, comparePrice: 269, stock: 130, sku: 'SV-BASE-GLYC-500' },
            { id: 'p10-v2', label: '1kg', price: 399, comparePrice: 459, stock: 90, sku: 'SV-BASE-GLYC-1KG' },
            { id: 'p10-v3', label: '5kg (Bulk)', price: 1799, comparePrice: 2099, stock: 25, sku: 'SV-BASE-GLYC-5KG' },
        ],
        rating: 4.6,
        reviews: [{ id: 'p10-r1', author: 'Neha J.', rating: 4, date: '2026-03-14', comment: 'Very clear finish, great for my layered soap designs.', verified: true }],
        tags: ['for-soap-makers'],
    },
    {
        id: 'p11',
        slug: 'multani-mitti-powder',
        name: "Multani Mitti (Fuller's Earth) Powder",
        category: 'herbal-powders',
        images: ['https://picsum.photos/seed/p11-multani-mitti-a/800/800', 'https://picsum.photos/seed/p11-multani-mitti-b/800/800', 'https://picsum.photos/seed/p11-multani-mitti-c/800/800'],
        shortDescription: "100% natural Fuller's Earth to absorb excess oil and refresh tired skin.",
        description: 'A finely sieved, 100% natural Multani Mitti sourced for skincare and soap making use. A staple in Indian skincare routines for its oil-absorbing and cooling properties.',
        benefits: ['Absorbs excess oil', 'Deep cleanses pores', 'Cools & soothes skin', 'Ideal for face packs & soap making'],
        ingredients: ["100% Pure Multani Mitti (Fuller's Earth)"],
        howToUse: ['Mix 2 tbsp powder with rose water or plain water to form a paste.', 'Apply an even layer to clean face, avoiding the eye area.', 'Leave on until semi-dry (10-15 minutes).', 'Rinse off with lukewarm water.'],
        variants: [
            { id: 'p11-v1', label: '100g', price: 99, comparePrice: 129, stock: 200, sku: 'SV-PWD-MMITTI-100' },
            { id: 'p11-v2', label: '250g', price: 199, comparePrice: 249, stock: 140, sku: 'SV-PWD-MMITTI-250' },
            { id: 'p11-v3', label: '500g', price: 349, comparePrice: 429, stock: 80, sku: 'SV-PWD-MMITTI-500' },
        ],
        rating: 4.5,
        reviews: [{ id: 'p11-r1', author: 'Ritu B.', rating: 5, date: '2026-02-27', comment: 'Great quality, very fine texture. Use it weekly as a face pack.', verified: true }],
        tags: [],
    },
    {
        id: 'p12',
        slug: 'manjistha-herbal-powder',
        name: 'Manjistha Herbal Powder',
        category: 'herbal-powders',
        images: ['https://picsum.photos/seed/p12-manjistha-a/800/800', 'https://picsum.photos/seed/p12-manjistha-b/800/800', 'https://picsum.photos/seed/p12-manjistha-c/800/800'],
        shortDescription: 'Skin-brightening Manjistha root powder, popular in Ayurvedic face packs & soaps.',
        description: 'Manjistha (Rubia Cordifolia) is a well-known herb in Ayurveda, often used in face packs and as a natural colorant in handmade soaps for its skin-loving reputation.',
        benefits: ['Traditionally used to help even out skin tone', 'A classic Ayurvedic skin herb', 'Popular as a natural handmade soap colorant', 'Antioxidant rich'],
        ingredients: ['100% Pure Manjistha (Rubia Cordifolia) Root Powder'],
        howToUse: ['Mix with water, honey or yogurt to form a face pack paste.', 'Apply for 15-20 minutes, then rinse.', 'For soap making, add 1-2 tsp per 500g base at trace.'],
        variants: [
            { id: 'p12-v1', label: '100g', price: 149, comparePrice: 179, stock: 100, sku: 'SV-PWD-MANJ-100' },
            { id: 'p12-v2', label: '250g', price: 329, comparePrice: 389, stock: 60, sku: 'SV-PWD-MANJ-250' },
        ],
        rating: 4.4,
        reviews: [{ id: 'p12-r1', author: 'Shalini T.', rating: 4, date: '2026-01-19', comment: 'Nice natural pink tint to my soap batches. Good quality powder.', verified: true }],
        tags: [],
    },
    {
        id: 'p13',
        slug: 'lavender-essential-oil',
        name: 'Lavender Essential Oil',
        category: 'essential-oils',
        images: ['https://picsum.photos/seed/p13-lavender-eo-a/800/800', 'https://picsum.photos/seed/p13-lavender-eo-b/800/800', 'https://picsum.photos/seed/p13-lavender-eo-c/800/800'],
        shortDescription: 'Pure steam-distilled lavender oil for soap making, diffusers & massage blends.',
        description: 'Steam-distilled from Lavandula Angustifolia flowers, this undiluted essential oil is a favorite among home soap makers and aromatherapy enthusiasts alike for its calming, floral scent.',
        benefits: ['Calming aromatherapy scent', 'A popular choice in cold-process soap making', 'Multipurpose - skin, hair & diffuser use', 'Steam-distilled & undiluted'],
        ingredients: ['100% Pure Lavandula Angustifolia (Lavender) Oil'],
        howToUse: [
            'Always dilute in a carrier oil before applying to skin (2-3 drops per 10ml carrier oil).',
            'For soap making, add 8-10ml per 1kg of soap base/oils at trace.',
            'Add 3-5 drops to a diffuser with water for aromatherapy.',
            'Perform a patch test 24 hours before first topical use.',
        ],
        variants: [
            { id: 'p13-v1', label: '10ml', price: 199, comparePrice: 229, stock: 150, sku: 'SV-EO-LAV-10' },
            { id: 'p13-v2', label: '30ml', price: 499, comparePrice: 579, stock: 90, sku: 'SV-EO-LAV-30' },
            { id: 'p13-v3', label: '100ml', price: 1299, comparePrice: 1499, stock: 35, sku: 'SV-EO-LAV-100' },
        ],
        rating: 4.8,
        reviews: [{ id: 'p13-r1', author: 'Pooja S.', rating: 5, date: '2026-05-08', comment: 'Beautiful, true-to-scent lavender oil. Perfect for my soap batches.', verified: true }],
        tags: ['bestseller', 'for-soap-makers'],
        featured: true,
        bestseller: true,
    },
    {
        id: 'p14',
        slug: 'tea-tree-essential-oil',
        name: 'Tea Tree Essential Oil',
        category: 'essential-oils',
        images: ['https://picsum.photos/seed/p14-teatree-eo-a/800/800', 'https://picsum.photos/seed/p14-teatree-eo-b/800/800', 'https://picsum.photos/seed/p14-teatree-eo-c/800/800'],
        shortDescription: 'Pure tea tree oil valued for its purifying properties in skincare & soap making.',
        description: 'Steam-distilled from Melaleuca Alternifolia leaves, our tea tree oil is undiluted and unblended - ideal for DIY skincare formulations and soap making projects that call for a purifying, fresh scent.',
        benefits: ['Naturally purifying scent profile', 'Popular in acne-prone skin formulations', 'Great for soap making & DIY skincare', 'Steam-distilled & undiluted'],
        ingredients: ['100% Pure Melaleuca Alternifolia (Tea Tree) Oil'],
        howToUse: ['Always dilute before topical use (1-2 drops per 10ml carrier oil).', 'For soap making, add 8-10ml per 1kg of base at trace.', 'Patch test before first use.'],
        variants: [
            { id: 'p14-v1', label: '10ml', price: 179, comparePrice: 209, stock: 160, sku: 'SV-EO-TTREE-10' },
            { id: 'p14-v2', label: '30ml', price: 449, comparePrice: 519, stock: 85, sku: 'SV-EO-TTREE-30' },
            { id: 'p14-v3', label: '100ml', price: 1199, comparePrice: 1399, stock: 30, sku: 'SV-EO-TTREE-100' },
        ],
        rating: 4.6,
        reviews: [{ id: 'p14-r1', author: 'Arjun D.', rating: 5, date: '2026-04-30', comment: 'Strong and pure, exactly as described. Great for my DIY face wash.', verified: true }],
        tags: ['for-soap-makers'],
    },
    {
        id: 'p15',
        slug: 'beginners-soap-making-kit',
        name: "Beginner's Soap Making DIY Kit",
        category: 'soap-making-kits',
        images: ['https://picsum.photos/seed/p15-beginner-kit-a/800/800', 'https://picsum.photos/seed/p15-beginner-kit-b/800/800', 'https://picsum.photos/seed/p15-beginner-kit-c/800/800'],
        shortDescription: "Everything a first-timer needs to make 5 batches of melt & pour soap at home.",
        description: 'Designed for absolute beginners, this kit includes a melt & pour base, fragrance oils, natural colorants, silicone moulds and an illustrated step-by-step guide so you can make your first batch of soap the same day it arrives.',
        benefits: ['Complete kit - no extra purchases needed', 'Step-by-step illustrated guide included', 'Safe for beginners & teens (with adult supervision)', 'Makes a great gifting option'],
        ingredients: ['Melt & Pour Soap Base (1kg)', '3 Fragrance Oils', '3 Natural Colorants', 'Silicone Mould Set (6 cavities)', 'Mixing Bowl & Stirrer', 'Printed Instruction Guide'],
        howToUse: [
            'Read through the printed guide before starting.',
            'Melt the soap base cubes in the provided bowl using a double-boiler or microwave.',
            'Stir in your chosen fragrance and colorant.',
            'Pour into the silicone moulds and let set for 3-4 hours.',
            'Unmould, trim if needed, and your soaps are ready to use or gift.',
        ],
        variants: [{ id: 'p15-v1', label: 'Beginner Kit', price: 799, comparePrice: 999, stock: 70, sku: 'SV-KIT-BEGIN' }],
        rating: 4.7,
        reviews: [{ id: 'p15-r1', author: 'Simran K.', rating: 5, date: '2026-06-05', comment: 'Bought this for my daughter and we made soaps together over the weekend - so much fun!', verified: true }],
        tags: ['kits', 'gifting', 'bestseller'],
        bestseller: true,
    },
    {
        id: 'p16',
        slug: 'advanced-cold-process-soap-kit',
        name: 'Advanced Cold Process Soap Kit',
        category: 'soap-making-kits',
        images: ['https://picsum.photos/seed/p16-advanced-kit-a/800/800', 'https://picsum.photos/seed/p16-advanced-kit-b/800/800', 'https://picsum.photos/seed/p16-advanced-kit-c/800/800'],
        shortDescription: 'A pro-level kit for cold-process soap making with lye, oils, moulds & safety gear.',
        description: 'Built for makers ready to move beyond melt & pour, this kit includes a curated coconut-olive-castor oil blend, lye, a silicone loaf mould and the safety gear you need to make approximately 4kg of true cold-process soap.',
        benefits: ['Includes safety gear (gloves & goggles)', 'Curated oil blend for a balanced, long-lasting bar', 'Enough supplies for approx. 4kg of soap', 'Includes digital thermometer & pH strips'],
        ingredients: ['Coconut, Olive & Castor Oil Blend', 'Sodium Hydroxide (Lye)', 'Silicone Loaf Mould', 'Safety Gloves & Goggles', 'Digital Thermometer', 'pH Strips', 'Printed Cold-Process Guide'],
        howToUse: [
            'Work in a well-ventilated area and always wear the provided gloves and goggles.',
            'Always add lye to water, never water to lye, and stir until fully dissolved.',
            'Bring oils and lye solution to the same target temperature (check with the digital thermometer) before combining.',
            'Blend to trace, pour into the mould, insulate and leave for 24-48 hours.',
            'Unmould, cut into bars and cure for 4-6 weeks before use, testing pH before regular use.',
        ],
        variants: [{ id: 'p16-v1', label: 'Advanced Kit', price: 1499, comparePrice: 1799, stock: 40, sku: 'SV-KIT-ADV' }],
        rating: 4.8,
        reviews: [{ id: 'p16-r1', author: 'Manoj R.', rating: 5, date: '2026-05-20', comment: 'Everything you need in one box. The guide is detailed and safety-focused.', verified: true }],
        tags: ['new', 'kits'],
        newArrival: true,
    },
];
export const getProductBySlug = (slug) => products.find((p) => p.slug === slug);
export const getProductsByCategory = (category) => products.filter((p) => p.category === category);
export const getRelatedProducts = (product, limit = 4) => products.filter((p) => p.category === product.category && p.id !== product.id).slice(0, limit);
